# Generated by Django 4.2.5 on 2023-10-09 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Contato",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=50)),
                ("email", models.EmailField(max_length=100)),
                ("mensagem", models.TextField()),
                ("data", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
